//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDataProvider")]
public interface IDataProvider
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProvider/TestMethod", ReplyAction="http://tempuri.org/IDataProvider/TestMethodResponse")]
    string TestMethod();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IDataProviderChannel : IDataProvider, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class DataProviderClient : System.ServiceModel.ClientBase<IDataProvider>, IDataProvider
{
    
    public DataProviderClient()
    {
    }
    
    public DataProviderClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DataProviderClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DataProviderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DataProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string TestMethod()
    {
        return base.Channel.TestMethod();
    }
}
