//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectionTest.HostWCFServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UPCData", Namespace="http://schemas.datacontract.org/2004/07/BEVMET_FULL_BAR.PourEngine")]
    [System.SerializableAttribute()]
    public partial class UPCData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short AmountInBottleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short BottleSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float NozzleDiameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, double> ViscocityByTemperatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short AmountInBottle {
            get {
                return this.AmountInBottleField;
            }
            set {
                if ((this.AmountInBottleField.Equals(value) != true)) {
                    this.AmountInBottleField = value;
                    this.RaisePropertyChanged("AmountInBottle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short BottleSize {
            get {
                return this.BottleSizeField;
            }
            set {
                if ((this.BottleSizeField.Equals(value) != true)) {
                    this.BottleSizeField = value;
                    this.RaisePropertyChanged("BottleSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float NozzleDiameter {
            get {
                return this.NozzleDiameterField;
            }
            set {
                if ((this.NozzleDiameterField.Equals(value) != true)) {
                    this.NozzleDiameterField = value;
                    this.RaisePropertyChanged("NozzleDiameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagID {
            get {
                return this.TagIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TagIDField, value) != true)) {
                    this.TagIDField = value;
                    this.RaisePropertyChanged("TagID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, double> ViscocityByTemperature {
            get {
                return this.ViscocityByTemperatureField;
            }
            set {
                if ((object.ReferenceEquals(this.ViscocityByTemperatureField, value) != true)) {
                    this.ViscocityByTemperatureField = value;
                    this.RaisePropertyChanged("ViscocityByTemperature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EngineSettings", Namespace="http://schemas.datacontract.org/2004/07/BEVMET_FULL_BAR.PourEngine")]
    [System.SerializableAttribute()]
    public partial class EngineSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, float> FormulaValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SleepTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Formula {
            get {
                return this.FormulaField;
            }
            set {
                if ((object.ReferenceEquals(this.FormulaField, value) != true)) {
                    this.FormulaField = value;
                    this.RaisePropertyChanged("Formula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, float> FormulaValues {
            get {
                return this.FormulaValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.FormulaValuesField, value) != true)) {
                    this.FormulaValuesField = value;
                    this.RaisePropertyChanged("FormulaValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress {
            get {
                return this.IPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAddressField, value) != true)) {
                    this.IPAddressField = value;
                    this.RaisePropertyChanged("IPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Port {
            get {
                return this.PortField;
            }
            set {
                if ((this.PortField.Equals(value) != true)) {
                    this.PortField = value;
                    this.RaisePropertyChanged("Port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short SleepTime {
            get {
                return this.SleepTimeField;
            }
            set {
                if ((this.SleepTimeField.Equals(value) != true)) {
                    this.SleepTimeField = value;
                    this.RaisePropertyChanged("SleepTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PourData", Namespace="http://schemas.datacontract.org/2004/07/BEVMET_FULL_BAR.PourEngine")]
    [System.SerializableAttribute()]
    public partial class PourData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BatteryVoltageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float LargePourAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PourAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PourCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan PourTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RawDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TemperatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BatteryVoltage {
            get {
                return this.BatteryVoltageField;
            }
            set {
                if ((this.BatteryVoltageField.Equals(value) != true)) {
                    this.BatteryVoltageField = value;
                    this.RaisePropertyChanged("BatteryVoltage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceID {
            get {
                return this.DeviceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIDField, value) != true)) {
                    this.DeviceIDField = value;
                    this.RaisePropertyChanged("DeviceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventID {
            get {
                return this.EventIDField;
            }
            set {
                if ((this.EventIDField.Equals(value) != true)) {
                    this.EventIDField = value;
                    this.RaisePropertyChanged("EventID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float LargePourAmount {
            get {
                return this.LargePourAmountField;
            }
            set {
                if ((this.LargePourAmountField.Equals(value) != true)) {
                    this.LargePourAmountField = value;
                    this.RaisePropertyChanged("LargePourAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PourAmount {
            get {
                return this.PourAmountField;
            }
            set {
                if ((this.PourAmountField.Equals(value) != true)) {
                    this.PourAmountField = value;
                    this.RaisePropertyChanged("PourAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PourCount {
            get {
                return this.PourCountField;
            }
            set {
                if ((this.PourCountField.Equals(value) != true)) {
                    this.PourCountField = value;
                    this.RaisePropertyChanged("PourCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan PourTime {
            get {
                return this.PourTimeField;
            }
            set {
                if ((this.PourTimeField.Equals(value) != true)) {
                    this.PourTimeField = value;
                    this.RaisePropertyChanged("PourTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RawData {
            get {
                return this.RawDataField;
            }
            set {
                if ((object.ReferenceEquals(this.RawDataField, value) != true)) {
                    this.RawDataField = value;
                    this.RaisePropertyChanged("RawData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagID {
            get {
                return this.TagIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TagIDField, value) != true)) {
                    this.TagIDField = value;
                    this.RaisePropertyChanged("TagID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Temperature {
            get {
                return this.TemperatureField;
            }
            set {
                if ((this.TemperatureField.Equals(value) != true)) {
                    this.TemperatureField = value;
                    this.RaisePropertyChanged("Temperature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TagPhase", Namespace="http://schemas.datacontract.org/2004/07/BEVMET_FULL_BAR.PourEngine")]
    [System.SerializableAttribute()]
    public partial class TagPhase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BatteryVoltageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EventTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConnectionTest.HostWCFServiceReference.TagPhaseType EventTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TemperatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BatteryVoltage {
            get {
                return this.BatteryVoltageField;
            }
            set {
                if ((this.BatteryVoltageField.Equals(value) != true)) {
                    this.BatteryVoltageField = value;
                    this.RaisePropertyChanged("BatteryVoltage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceID {
            get {
                return this.DeviceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIDField, value) != true)) {
                    this.DeviceIDField = value;
                    this.RaisePropertyChanged("DeviceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventID {
            get {
                return this.EventIDField;
            }
            set {
                if ((this.EventIDField.Equals(value) != true)) {
                    this.EventIDField = value;
                    this.RaisePropertyChanged("EventID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EventTime {
            get {
                return this.EventTimeField;
            }
            set {
                if ((this.EventTimeField.Equals(value) != true)) {
                    this.EventTimeField = value;
                    this.RaisePropertyChanged("EventTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConnectionTest.HostWCFServiceReference.TagPhaseType EventType {
            get {
                return this.EventTypeField;
            }
            set {
                if ((this.EventTypeField.Equals(value) != true)) {
                    this.EventTypeField = value;
                    this.RaisePropertyChanged("EventType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagID {
            get {
                return this.TagIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TagIDField, value) != true)) {
                    this.TagIDField = value;
                    this.RaisePropertyChanged("TagID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Temperature {
            get {
                return this.TemperatureField;
            }
            set {
                if ((this.TemperatureField.Equals(value) != true)) {
                    this.TemperatureField = value;
                    this.RaisePropertyChanged("Temperature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLMessage {
            get {
                return this.XMLMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLMessageField, value) != true)) {
                    this.XMLMessageField = value;
                    this.RaisePropertyChanged("XMLMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TagPhaseType", Namespace="http://schemas.datacontract.org/2004/07/BEVMET_FULL_BAR.PourEngine")]
    public enum TagPhaseType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Heartbeat = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Connect = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disconnect = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dormant = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissedPour = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissedMsg = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BadBottleAttach = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TagMoved = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceAlert", Namespace="http://schemas.datacontract.org/2004/07/BEVMET_FULL_BAR.PourEngine")]
    [System.SerializableAttribute()]
    public partial class DeviceAlert : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AlertTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConnectionTest.HostWCFServiceReference.DeviceAlertType AlertTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AlertTime {
            get {
                return this.AlertTimeField;
            }
            set {
                if ((this.AlertTimeField.Equals(value) != true)) {
                    this.AlertTimeField = value;
                    this.RaisePropertyChanged("AlertTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConnectionTest.HostWCFServiceReference.DeviceAlertType AlertType {
            get {
                return this.AlertTypeField;
            }
            set {
                if ((this.AlertTypeField.Equals(value) != true)) {
                    this.AlertTypeField = value;
                    this.RaisePropertyChanged("AlertType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceID {
            get {
                return this.DeviceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIDField, value) != true)) {
                    this.DeviceIDField = value;
                    this.RaisePropertyChanged("DeviceID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceAlertType", Namespace="http://schemas.datacontract.org/2004/07/BEVMET_FULL_BAR.PourEngine")]
    public enum DeviceAlertType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CannotConnect = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotReadingTags = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HostWCFServiceReference.IPourEngineService")]
    public interface IPourEngineService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPourEngineService/GetUPCByTag", ReplyAction="http://tempuri.org/IPourEngineService/GetUPCByTagResponse")]
        ConnectionTest.HostWCFServiceReference.UPCData GetUPCByTag(string tagID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPourEngineService/GetSettings", ReplyAction="http://tempuri.org/IPourEngineService/GetSettingsResponse")]
        ConnectionTest.HostWCFServiceReference.EngineSettings GetSettings(string deviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPourEngineService/PushPourData", ReplyAction="http://tempuri.org/IPourEngineService/PushPourDataResponse")]
        void PushPourData(ConnectionTest.HostWCFServiceReference.PourData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPourEngineService/PushTagEvent", ReplyAction="http://tempuri.org/IPourEngineService/PushTagEventResponse")]
        void PushTagEvent(ConnectionTest.HostWCFServiceReference.TagPhase data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPourEngineService/PushStoredEvents", ReplyAction="http://tempuri.org/IPourEngineService/PushStoredEventsResponse")]
        void PushStoredEvents(System.Collections.Generic.List<ConnectionTest.HostWCFServiceReference.TagPhase> data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPourEngineService/PushDeviceAlert", ReplyAction="http://tempuri.org/IPourEngineService/PushDeviceAlertResponse")]
        bool PushDeviceAlert(ConnectionTest.HostWCFServiceReference.DeviceAlert ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPourEngineService/SendStartEvent", ReplyAction="http://tempuri.org/IPourEngineService/SendStartEventResponse")]
        bool SendStartEvent();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPourEngineServiceChannel : ConnectionTest.HostWCFServiceReference.IPourEngineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PourEngineServiceClient : System.ServiceModel.ClientBase<ConnectionTest.HostWCFServiceReference.IPourEngineService>, ConnectionTest.HostWCFServiceReference.IPourEngineService {
        
        public PourEngineServiceClient() {
        }
        
        public PourEngineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PourEngineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PourEngineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PourEngineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConnectionTest.HostWCFServiceReference.UPCData GetUPCByTag(string tagID) {
            return base.Channel.GetUPCByTag(tagID);
        }
        
        public ConnectionTest.HostWCFServiceReference.EngineSettings GetSettings(string deviceID) {
            return base.Channel.GetSettings(deviceID);
        }
        
        public void PushPourData(ConnectionTest.HostWCFServiceReference.PourData data) {
            base.Channel.PushPourData(data);
        }
        
        public void PushTagEvent(ConnectionTest.HostWCFServiceReference.TagPhase data) {
            base.Channel.PushTagEvent(data);
        }
        
        public void PushStoredEvents(System.Collections.Generic.List<ConnectionTest.HostWCFServiceReference.TagPhase> data) {
            base.Channel.PushStoredEvents(data);
        }
        
        public bool PushDeviceAlert(ConnectionTest.HostWCFServiceReference.DeviceAlert ticket) {
            return base.Channel.PushDeviceAlert(ticket);
        }
        
        public bool SendStartEvent() {
            return base.Channel.SendStartEvent();
        }
    }
}
