//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Jaxis.DrinkInventory.Reporting.DataInterfaces;

namespace Jaxis.DrinkInventory.Reporting.Data.POCO
{
    
    public partial class Alert
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return AlertId; } set { AlertId = value; } }
    }
    
    public partial class AreaMembership
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return AreaMembershipId; } set { AreaMembershipId = value; } }
    }
    
    public partial class Area
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return AreaId; } set { AreaId = value; } }
    }
    
    public partial class Column
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return ColumnId; } set { ColumnId = value; } }
    }
    
    public partial class Device
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return DeviceId; } set { DeviceId = value; } }
    }
    
    public partial class Organization
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return OrganizationId; } set { OrganizationId = value; } }
    }
    
    public partial class Parameter
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return ParameterId; } set { ParameterId = value; } }
    }
    
    public partial class POSTicketItem
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return POSTicketItemId; } set { POSTicketItemId = value; } }
    }
    
    public partial class Pour
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return PourId; } set { PourId = value; } }
    }
    
    public partial class Report
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return ReportId; } set { ReportId = value; } }
    }
    
    public partial class Schema
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return SchemaId; } set { SchemaId = value; } }
    }
    
    public partial class SecurityView
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return SecurityViewId; } set { SecurityViewId = value; } }
    }
    
    public partial class Session
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return SessionId; } set { SessionId = value; } }
    }
    
    public partial class UPC
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return UPCId; } set { UPCId = value; } }
    }
    
    public partial class UserGroupMembership
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return UserGroupMembershipId; } set { UserGroupMembershipId = value; } }
    }
    
    public partial class UserGroup
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return UserGroupId; } set { UserGroupId = value; } }
    }
    
    public partial class UserGroupXOrganization
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return UserGroupXOrganizationId; } set { UserGroupXOrganizationId = value; } }
    }
    
    public partial class User
    {
    	[DataMember]
    	public bool IsNew{ get; set; }
    	[DataMember]
    	public Guid Id { get { return UserId; } set { UserId = value; } }
    }
}
