//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

namespace Jaxis.DrinkInventory.Reporting.DataInterfaces
{
	public partial interface IDataManager{ }

	public partial interface IDataManager<T> : IDataManager
	{
		T Create( );
		T Save( T _item );
		void Delete( T _item );
		void Delete( Guid _id );
		int Delete( Expression<Func<T, bool>> _predicate );
		IQueryable<T> GetAll( );
		T Get( Guid _id );
		void Hydrate( T _item, bool _includeRelatedObjects = false );
	}
	public partial interface IAlertManager : IDataManager<IAlert> { }
	public partial interface IAreaMembershipManager : IDataManager<IAreaMembership> { }
	public partial interface IAreaManager : IDataManager<IArea> { }
	public partial interface IColumnManager : IDataManager<IColumn> { }
	public partial interface IDeviceManager : IDataManager<IDevice> { }
	public partial interface IOrganizationManager : IDataManager<IOrganization> { }
	public partial interface IParameterManager : IDataManager<IParameter> { }
	public partial interface IPOSTicketItemManager : IDataManager<IPOSTicketItem> { }
	public partial interface IPourManager : IDataManager<IPour> { }
	public partial interface IReportManager : IDataManager<IReport> { }
	public partial interface ISchemaManager : IDataManager<ISchema> { }
	public partial interface ISecurityViewManager : IDataManager<ISecurityView> { }
	public partial interface ISessionManager : IDataManager<ISession> { }
	public partial interface IUPCManager : IDataManager<IUPC> { }
	public partial interface IUserGroupMembershipManager : IDataManager<IUserGroupMembership> { }
	public partial interface IUserGroupManager : IDataManager<IUserGroup> { }
	public partial interface IUserGroupXOrganizationManager : IDataManager<IUserGroupXOrganization> { }
	public partial interface IUserManager : IDataManager<IUser> { }
	public partial interface IDataManagerFactory : IDisposable
    {
		IAlertManager Alert { get; }
		IAreaMembershipManager AreaMembership { get; }
		IAreaManager Area { get; }
		IColumnManager Column { get; }
		IDeviceManager Device { get; }
		IOrganizationManager Organization { get; }
		IParameterManager Parameter { get; }
		IPOSTicketItemManager POSTicketItem { get; }
		IPourManager Pour { get; }
		IReportManager Report { get; }
		ISchemaManager Schema { get; }
		ISecurityViewManager SecurityView { get; }
		ISessionManager Session { get; }
		IUPCManager UPC { get; }
		IUserGroupMembershipManager UserGroupMembership { get; }
		IUserGroupManager UserGroup { get; }
		IUserGroupXOrganizationManager UserGroupXOrganization { get; }
		IUserManager User { get; }
		IDataManager<T> Manage<T>( );
		int SaveChanges( );
    }

}	// End of Namespace
