//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace PourControlsAPI.BevMonAPI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IBeverageManagementAPI", Namespace="http://tempuri.org/")]
    public partial class BeverageManagementAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPourInformationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BeverageManagementAPI() {
            this.Url = global::PourControlsAPI.Properties.Settings.Default.PourControlsAPI_BevMonAPI_BeverageManagementAPI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPourInformationCompletedEventHandler GetPourInformationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBeverageManagementAPI/GetPourInformation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Jaxis.BeverageManagement.Plugin")]
        public PourInformation[] GetPourInformation(System.DateTime _startTime, [System.Xml.Serialization.XmlIgnoreAttribute()] bool _startTimeSpecified, System.DateTime _endTime, [System.Xml.Serialization.XmlIgnoreAttribute()] bool _endTimeSpecified) {
            object[] results = this.Invoke("GetPourInformation", new object[] {
                        _startTime,
                        _startTimeSpecified,
                        _endTime,
                        _endTimeSpecified});
            return ((PourInformation[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPourInformationAsync(System.DateTime _startTime, bool _startTimeSpecified, System.DateTime _endTime, bool _endTimeSpecified) {
            this.GetPourInformationAsync(_startTime, _startTimeSpecified, _endTime, _endTimeSpecified, null);
        }
        
        /// <remarks/>
        public void GetPourInformationAsync(System.DateTime _startTime, bool _startTimeSpecified, System.DateTime _endTime, bool _endTimeSpecified, object userState) {
            if ((this.GetPourInformationOperationCompleted == null)) {
                this.GetPourInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPourInformationOperationCompleted);
            }
            this.InvokeAsync("GetPourInformation", new object[] {
                        _startTime,
                        _startTimeSpecified,
                        _endTime,
                        _endTimeSpecified}, this.GetPourInformationOperationCompleted, userState);
        }
        
        private void OnGetPourInformationOperationCompleted(object arg) {
            if ((this.GetPourInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPourInformationCompleted(this, new GetPourInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Jaxis.BeverageManagement.Plugin")]
    public partial class PourInformation {
        
        private double amountLeftField;
        
        private bool amountLeftFieldSpecified;
        
        private double batteryVoltageField;
        
        private bool batteryVoltageFieldSpecified;
        
        private string categoryField;
        
        private string deviceNameField;
        
        private string itemNumberField;
        
        private string locationNameField;
        
        private string manufacturerField;
        
        private double pourAmountField;
        
        private bool pourAmountFieldSpecified;
        
        private System.DateTime pourTimeField;
        
        private bool pourTimeFieldSpecified;
        
        private string rootCategoryField;
        
        private string tagNumberField;
        
        private double temperatureField;
        
        private bool temperatureFieldSpecified;
        
        private string uPCNameField;
        
        private int uPCSizeField;
        
        private bool uPCSizeFieldSpecified;
        
        /// <remarks/>
        public double AmountLeft {
            get {
                return this.amountLeftField;
            }
            set {
                this.amountLeftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountLeftSpecified {
            get {
                return this.amountLeftFieldSpecified;
            }
            set {
                this.amountLeftFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double BatteryVoltage {
            get {
                return this.batteryVoltageField;
            }
            set {
                this.batteryVoltageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BatteryVoltageSpecified {
            get {
                return this.batteryVoltageFieldSpecified;
            }
            set {
                this.batteryVoltageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeviceName {
            get {
                return this.deviceNameField;
            }
            set {
                this.deviceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LocationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
        
        /// <remarks/>
        public double PourAmount {
            get {
                return this.pourAmountField;
            }
            set {
                this.pourAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PourAmountSpecified {
            get {
                return this.pourAmountFieldSpecified;
            }
            set {
                this.pourAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PourTime {
            get {
                return this.pourTimeField;
            }
            set {
                this.pourTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PourTimeSpecified {
            get {
                return this.pourTimeFieldSpecified;
            }
            set {
                this.pourTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RootCategory {
            get {
                return this.rootCategoryField;
            }
            set {
                this.rootCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TagNumber {
            get {
                return this.tagNumberField;
            }
            set {
                this.tagNumberField = value;
            }
        }
        
        /// <remarks/>
        public double Temperature {
            get {
                return this.temperatureField;
            }
            set {
                this.temperatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TemperatureSpecified {
            get {
                return this.temperatureFieldSpecified;
            }
            set {
                this.temperatureFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UPCName {
            get {
                return this.uPCNameField;
            }
            set {
                this.uPCNameField = value;
            }
        }
        
        /// <remarks/>
        public int UPCSize {
            get {
                return this.uPCSizeField;
            }
            set {
                this.uPCSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UPCSizeSpecified {
            get {
                return this.uPCSizeFieldSpecified;
            }
            set {
                this.uPCSizeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPourInformationCompletedEventHandler(object sender, GetPourInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPourInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPourInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PourInformation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PourInformation[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591