//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("http://www.JaxisSolutions.com/")]
[assembly: AssemblyProduct("EdgeBase Service")]
[assembly: AssemblyCopyright("Copyright © Jaxis Custom Solutions, Inc. 2011")]
[assembly: AssemblyVersion("1.0.0.484")]
[assembly: AssemblyFileVersion("1.0.0.484")]
[assembly: AssemblyDelaySign(false)]


